# Generated by Django 6.0.3 on 2026-04-11 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.IntegerField(default=9265186613)),
                ('bizName', models.CharField(max_length=255)),
                ('bizType', models.CharField(max_length=255)),
                ('Gstin', models.CharField(default='')),
                ('City', models.CharField(max_length=255)),
                ('full_address', models.TextField(default='')),
                ('Pan_number', models.CharField(default='', max_length=15)),
                ('Gst_enable', models.BooleanField(default=True)),
                ('default_gst', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_name', models.CharField(max_length=255)),
                ('Customer_mobile', models.IntegerField()),
                ('Customer_email', models.EmailField(default='customer@smartbill.com', max_length=254)),
                ('customer_bill_count', models.IntegerField(default=0)),
                ('customer_bill_spent', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Formet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Inv_prefix', models.CharField(default='INV-')),
                ('Inv_footer', models.CharField(default='Thank you for your purchase! For queries, contact us at shop@billmate.in')),
                ('Inv_due_days', models.IntegerField(default=15)),
                ('Show_signature_area', models.BooleanField(default=True)),
                ('Show_TC', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Inv_number', models.IntegerField()),
                ('Inv_Total', models.FloatField()),
                ('Inv_subtotal', models.FloatField()),
                ('Inv_gst', models.FloatField()),
                ('Inv_discount', models.FloatField()),
                ('Inv_additional_charges', models.FloatField()),
                ('Inv_internal_notes', models.TextField()),
                ('Inv_bill_date', models.DateField()),
                ('Inv_due_bill_date', models.DateField()),
                ('Inv_payment_mode', models.CharField()),
                ('Customer_number', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField()),
                ('Product_price', models.IntegerField(default=0)),
                ('Product_stock', models.IntegerField(default=0)),
                ('Product_gst', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sells',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField()),
                ('Product_qty', models.IntegerField()),
                ('Product_price', models.IntegerField()),
                ('Product_gst', models.IntegerField(default=0)),
                ('Inv_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myweb.invoice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
